[project]
name = "flowlauncher-tags"
version = "1.0.0"
dependencies = [
    "flogin @ git+https://github.com/4d48/flogin.git",
    "Pillow",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.basedpyright]
typeCheckingMode = "all"
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
pythonpath = ["."]
